In [1]:
#Research Question: Can we use Market Basket Analysis to identify customer purchasing association behavior?

In [2]:
#Standard Analysis imports:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
#Importing Data:
df = pd.read_csv('C:\\Users\\weepo\\Documents\\WGU\\D212\\task 3\\teleco_market_basket.csv')

In [4]:
#testing
df.head()

,Item01,Item02,Item03,Item04,Item05,Item06,Item07,Item08,Item09,Item10,Item11,Item12,Item13,Item14,Item15,Item16,Item17,Item18,Item19,Item20
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Logitech M510 Wireless mouse,HP 63 Ink,HP 65 ink,nonda USB C to USB Adapter,10ft iPHone Charger Cable,HP 902XL ink,Creative Pebble 2.0 Speakers,Cleaning Gel Universal Dust Cleaner,Micro Center 32GB Memory card,YUNSONG 3pack 6ft Nylon Lightning Cable,TopMate C5 Laptop Cooler pad,Apple USB-C Charger cable,HyperX Cloud Stinger Headset,TONOR USB Gaming Microphone,Dust-Off Compressed Gas 2 pack,3A USB Type C Cable 3 pack 6FT,HOVAMP iPhone charger,SanDisk Ultra 128GB card,FEEL2NICE 5 pack 10ft Lighning cable,FEIYOLD Blue light Blocking Glasses
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Apple Lightning to Digital AV Adapter,TP-Link AC1750 Smart WiFi Router,Apple Pencil,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df.shape

(15002, 20)

In [6]:
#Checking nulls
df.isna().any()

Item01    True
Item02    True
Item03    True
Item04    True
Item05    True
Item06    True
Item07    True
Item08    True
Item09    True
Item10    True
Item11    True
Item12    True
Item13    True
Item14    True
Item15    True
Item16    True
Item17    True
Item18    True
Item19    True
Item20    True
dtype: bool

In [7]:
#Dropping rows with no entries
df2=df[df['Item01'].notna()]

In [8]:
#Rechecking
df2.isna().any()

Item01    False
Item02     True
Item03     True
Item04     True
Item05     True
Item06     True
Item07     True
Item08     True
Item09     True
Item10     True
Item11     True
Item12     True
Item13     True
Item14     True
Item15     True
Item16     True
Item17     True
Item18     True
Item19     True
Item20     True
dtype: bool

In [9]:
#Removing null values buy swapping with 0
df3=df2.fillna(0)

In [10]:
#Recheckingd
df3.isna().any()

Item01    False
Item02    False
Item03    False
Item04    False
Item05    False
Item06    False
Item07    False
Item08    False
Item09    False
Item10    False
Item11    False
Item12    False
Item13    False
Item14    False
Item15    False
Item16    False
Item17    False
Item18    False
Item19    False
Item20    False
dtype: bool

In [11]:
df3.shape

(7501, 20)

In [12]:
#Transforming Data w/ TransactionEncoder
#Code sourced from either Dr. Kamara's videos or
#https://rasbt.github.io/mlxtend/USER_GUIDE_INDEX/
from mlxtend.preprocessing import TransactionEncoder
#Convert to lists
rows = []
for i in range (0, 7501):
    rows.append([str(df2.values[i,j])
for j in range (0, 20)])

In [13]:
#TransactionEncoder from mlxtend
DE = TransactionEncoder()
array = DE.fit(rows).transform(rows)
transaction = pd.DataFrame(array, columns = DE.columns_)
transaction

,10ft iPHone Charger Cable,10ft iPHone Charger Cable 2 Pack,3 pack Nylon Braided Lightning Cable,3A USB Type C Cable 3 pack 6FT,5pack Nylon Braided USB C cables,ARRIS SURFboard SB8200 Cable Modem,Anker 2-in-1 USB Card Reader,Anker 4-port USB hub,Anker USB C to HDMI Adapter,Apple Lightning to Digital AV Adapter,...,iFixit Pro Tech Toolkit,iPhone 11 case,iPhone 12 Charger cable,iPhone 12 Pro case,iPhone 12 case,iPhone Charger Cable Anker 6ft,iPhone SE case,nan,nonda USB C to USB Adapter,seenda Wireless mouse
0,True,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
1,False,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,True,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7496,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
7497,False,False,False,False,False,True,False,False,False,True,...,False,False,False,False,False,False,False,True,False,False
7498,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
7499,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
7500,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False

In [14]:
#List of columns
for col in transaction.columns:
    print(col)

10ft iPHone Charger Cable
10ft iPHone Charger Cable 2 Pack
3 pack Nylon Braided Lightning Cable
3A USB Type C Cable 3 pack 6FT
5pack Nylon Braided USB C cables
ARRIS SURFboard SB8200 Cable Modem
Anker 2-in-1 USB Card Reader
Anker 4-port USB hub
Anker USB C to HDMI Adapter
Apple Lightning to Digital AV Adapter
Apple Lightning to USB cable
Apple Magic Mouse 2
Apple Pencil
Apple Pencil 2nd Gen
Apple Power Adapter Extension Cable
Apple USB-C Charger cable
AutoFocus 1080p Webcam
BENGOO G90000 headset
Blue Light Blocking Glasses
Blue Light Blocking Glasses 2pack
Brother Genuine High Yield Toner Cartridge
Cat 6 Ethernet Cable 50ft
Cat8 Ethernet Cable
CicTsing MM057 2.4G Wireless Mouse
Cleaning Gel Universal Dust Cleaner
Creative Pebble 2.0 Speakers
DisplayPort ot HDMI adapter
Dust-Off Compressed Gas
Dust-Off Compressed Gas 2 pack
FEEL2NICE 5 pack 10ft Lighning cable
FEIYOLD Blue light Blocking Glasses
Falcon Dust Off Compressed Gas
HOVAMP Mfi 6pack Lightning Cable
HOVAMP iPhone charger
HP 61 2 pack ink
HP 61 Tri-color ink
HP 61 ink
HP 62XL Tri-Color ink
HP 62XL ink
HP 63 Ink
HP 63 Tri-color ink
HP 63XL Ink
HP 63XL Tri-color ink
HP 64 Tri-Color ink
HP 64 ink
HP 65 ink
HP 902XL ink
HP 952 ink
HP ENVY 5055 printer
HP952XL ink
HooToo USB C Hub
HyperX Cloud Stinger Headset
Jelly Comb 2.4G Slim Wireless mouse
Leader Desk Pad Protector
Logitech M510 Wireless mouse
Logitech MK270 Wireless Keyboard/Mouse
Logitech MK345 Wireless combo
Logitech USB H390 headset
M.2 Screw kit
Mfi-Certified Lightning to USB A Cable
Micro Center 32GB Memory card
Microsot Surface Dock 2
Moread HDMI to VGA Adapter
Mpow HC6 USB Headset
NETGEAR CM500 Cable Modem
NETGEAR Nighthawk WiFi Router
NETGEAR Orbi Home Mesh WiFi System
Nylon Braided Lightning to USB cable
PS4 Headset
Premium Nylon USB Cable
RUNMUS Gaming Headset
SAMSUNG 128GB card
SAMSUNG 256 GB card
SAMSUNG EVO 32GB card
SAMSUNG EVO 64GB card
Sabrent 4-port USB 3.0 hub
SanDisk 128GB Ultra microSDXC card
SanDisk 128GB card
SanDisk 128GB microSDXC card
SanDisk 32GB Ultra SDHC card
SanDisk 32GB card
SanDisk Extreme 128GB card
SanDisk Extreme 256GB card
SanDisk Extreme 32GB 2pack card
SanDisk Extreme Pro 128GB card
SanDisk Extreme Pro 64GB card
SanDisk Ultra 128GB card
SanDisk Ultra 256GB card
SanDisk Ultra 400GB card
SanDisk Ultra 64GB card
Screen Mom Screen Cleaner kit
Stylus Pen for iPad
Syntech USB C to USB Adapter
TONOR USB Gaming Microphone
TP-Link AC1750 Smart WiFi Router
TP-Link AC4000 WiFi router
TopMate C5 Laptop Cooler pad
UNEN Mfi Certified 5-pack Lightning Cable
USB 2.0 Printer cable
USB C to USB Male Adapter
USB Type C Cable
USB Type C to USB-A Charger cable
VIVO Dual LCD Monitor Desk mount
VicTsing Mouse Pad
VicTsing Wireless mouse
Vsco 70 pack stickers
Webcam with Microphone
XPOWER A-2 Air Pump blower
YUNSONG 3pack 6ft Nylon Lightning Cable
hP 65 Tri-color ink
iFixit Pro Tech Toolkit
iPhone 11 case
iPhone 12 Charger cable
iPhone 12 Pro case
iPhone 12 case
iPhone Charger Cable Anker 6ft
iPhone SE case
nan
nonda USB C to USB Adapter
seenda Wireless mouse

In [15]:
#Checking for empty columns and removing
df4 = transaction.drop(['nan'], axis = 1)
df4.head(7505)

,10ft iPHone Charger Cable,10ft iPHone Charger Cable 2 Pack,3 pack Nylon Braided Lightning Cable,3A USB Type C Cable 3 pack 6FT,5pack Nylon Braided USB C cables,ARRIS SURFboard SB8200 Cable Modem,Anker 2-in-1 USB Card Reader,Anker 4-port USB hub,Anker USB C to HDMI Adapter,Apple Lightning to Digital AV Adapter,...,hP 65 Tri-color ink,iFixit Pro Tech Toolkit,iPhone 11 case,iPhone 12 Charger cable,iPhone 12 Pro case,iPhone 12 case,iPhone Charger Cable Anker 6ft,iPhone SE case,nonda USB C to USB Adapter,seenda Wireless mouse
0,True,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
1,False,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7496,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7497,False,False,False,False,False,True,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
7498,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7499,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7500,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [16]:
df4.to_csv('C:\\Users\\weepo\\Documents\\WGU\\D212\\task 3\\teleco_market_basket_cleaned.csv')

In [17]:
#Apriori time
#Code sourced from either Dr. Kamara's videos or
#https://rasbt.github.io/mlxtend/USER_GUIDE_INDEX/
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules
rules = apriori(df4, min_support = 0.02, use_colnames = True)
rules.head(5)

    support                                 itemsets
0  0.050527       (10ft iPHone Charger Cable 2 Pack)
1  0.042528         (3A USB Type C Cable 3 pack 6FT)
2  0.029463           (Anker 2-in-1 USB Card Reader)
3  0.068391            (Anker USB C to HDMI Adapter)
4  0.087188  (Apple Lightning to Digital AV Adapter)

In [18]:
#Rules table
rulestable = association_rules(rules, metric = 'lift', min_threshold = 1)
rulestable.head(10)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(10ft iPHone Charger Cable 2 Pack),(Dust-Off Compressed Gas 2 pack),0.050527,0.238368,0.023064,0.456464,1.914955,1.0,0.011020,1.401255,0.503221,0.086760,0.286354,0.276610
1,(Dust-Off Compressed Gas 2 pack),(10ft iPHone Charger Cable 2 Pack),0.238368,0.050527,0.023064,0.096756,1.914955,1.0,0.011020,1.051182,0.627330,0.086760,0.048690,0.276610
2,(Anker USB C to HDMI Adapter),(Dust-Off Compressed Gas 2 pack),0.068391,0.238368,0.024397,0.356725,1.496530,1.0,0.008095,1.183991,0.356144,0.086402,0.155399,0.229537
3,(Dust-Off Compressed Gas 2 pack),(Anker USB C to HDMI Adapter),0.238368,0.068391,0.024397,0.102349,1.496530,1.0,0.008095,1.037830,0.435627,0.086402,0.036451,0.229537
4,(VIVO Dual LCD Monitor Desk mount),(Anker USB C to HDMI Adapter),0.174110,0.068391,0.020931,0.120214,1.757755,1.0,0.009023,1.058905,0.521973,0.094465,0.055628,0.213129
5,(Anker USB C to HDMI Adapter),(VIVO Dual LCD Monitor Desk mount),0.068391,0.174110,0.020931,0.306043,1.757755,1.0,0.009023,1.190117,0.462740,0.094465,0.159746,0.213129
6,(Apple Lightning to Digital AV Adapter),(Apple Pencil),0.087188,0.179709,0.028796,0.330275,1.837830,1.0,0.013128,1.224818,0.499424,0.120941,0.183552,0.245256
7,(Apple Pencil),(Apple Lightning to Digital AV Adapter),0.179709,0.087188,0.028796,0.160237,1.837830,1.0,0.013128,1.086988,0.555754,0.120941,0.080026,0.245256
8,(Apple Lightning to Digital AV Adapter),(Dust-Off Compressed Gas 2 pack),0.087188,0.238368,0.024397,0.279817,1.173883,1.0,0.003614,1.057552,0.162275,0.081009,0.054420,0.191083
9,(Dust-Off Compressed Gas 2 pack),(Apple Lightning to Digital AV Adapter),0.238368,0.087188,0.024397,0.102349,1.173883,1.0,0.003614,1.016889,0.194486,0.081009,0.016609,0.191083

In [19]:
#following code is for showing top 3 rules for each metric
top3 = rulestable.sort_values('confidence', ascending=False).head(3)
top3

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(10ft iPHone Charger Cable 2 Pack),(Dust-Off Compressed Gas 2 pack),0.050527,0.238368,0.023064,0.456464,1.914955,1.0,0.011020,1.401255,0.503221,0.086760,0.286354,0.276610
36,(FEIYOLD Blue light Blocking Glasses),(Dust-Off Compressed Gas 2 pack),0.065858,0.238368,0.027596,0.419028,1.757904,1.0,0.011898,1.310962,0.461536,0.099759,0.237201,0.267400
52,(SanDisk Ultra 64GB card),(Dust-Off Compressed Gas 2 pack),0.098254,0.238368,0.040928,0.416554,1.747522,1.0,0.017507,1.305401,0.474369,0.138413,0.233952,0.294127

In [20]:
top3 = rulestable.sort_values('lift', ascending=False).head(3)
top3

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
85,(VIVO Dual LCD Monitor Desk mount),(SanDisk Ultra 64GB card),0.174110,0.098254,0.039195,0.225115,2.291162,1.0,0.022088,1.163716,0.682343,0.168096,0.140684,0.312015
84,(SanDisk Ultra 64GB card),(VIVO Dual LCD Monitor Desk mount),0.098254,0.174110,0.039195,0.398915,2.291162,1.0,0.022088,1.373997,0.624943,0.168096,0.272197,0.312015
65,(FEIYOLD Blue light Blocking Glasses),(VIVO Dual LCD Monitor Desk mount),0.065858,0.174110,0.022930,0.348178,1.999758,1.0,0.011464,1.267048,0.535186,0.105651,0.210764,0.239939

In [21]:
top3 = rulestable.sort_values('support', ascending=False).head(3)
top3

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
62,(VIVO Dual LCD Monitor Desk mount),(Dust-Off Compressed Gas 2 pack),0.174110,0.238368,0.059725,0.343032,1.439085,1.0,0.018223,1.159314,0.369437,0.169312,0.137421,0.296796
63,(Dust-Off Compressed Gas 2 pack),(VIVO Dual LCD Monitor Desk mount),0.238368,0.174110,0.059725,0.250559,1.439085,1.0,0.018223,1.102008,0.400606,0.169312,0.092566,0.296796
41,(Dust-Off Compressed Gas 2 pack),(HP 61 ink),0.238368,0.163845,0.052660,0.220917,1.348332,1.0,0.013604,1.073256,0.339197,0.150648,0.068256,0.271158